    % PMSM motor parameters

L = 40.03/1000;            %1 inductance of the stator windings [H]]
R = 8.875;              %1 resistance of the stator windings [Ohm]
Jm =60/1000000;            %1 motor inertia [kg*m^2]
np = 5;                 %1 motor pole pair
lambda_m = 0.2086;      %1 magnetic flux, generated by permanent magnets [Wb]
B=0;                    %viscous friction coefficient
tao_L=1;  %1 

v=1400;
a1=80;
a2=200;
a3=360;
a4=520;
gamma_eta=1;
gamma_lambda=900000000;
Kp=2000;
Ki=10000;

% Initial conditions (values of the state variables at t=0 sec)

ia0=0;
ib0=0; 
omega0=0;
theta0=0;

%
% alpha=15;
% gamma=1;
% xiPLL = 0.07;
% w0PLL = 250*pi;
% Kp=2*xiPLL*(w0PLL - 200*pi);
% Ki=w0PLL^2  * 20;
